### ISSUE TITLE
question: Exercise 5, less render than you

### ISSUE THREAD

**Issue by gabbloquet** [kentcdodds/react-performance#58]
Hey @kentcdodds ,

Thanks a lot for this great course.
I have a question about 5th exercise, i have less renders than you without any change : 
![image](https://user-images.githubusercontent.com/25029077/98838154-290c9a80-2444-11eb-8f95-ff0ee1d8a6c6.png)

Do you know why ? Maybe a flamegraph bug ? 🤔
Because i have all cells in ranked.

Thanks a lot, have a nice day :)

**Comment by kentcdodds** [comment]
> Because i have all cells in ranked.

The Flamegraph doesn't show everything when you have a lot of components because I guess there's too much to show or something. It's unclear to me, but that feels like a bug.

When you really want to get an idea of everything that rendered, then you'll want to check the ranked view because that will show everything that rendered.

I hope that helps!
